= Changelog

All notable changes to this project will be documented in this file.

The format is based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog] and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

== [nng-rs Unreleased] ==

=== Added ===

* The `Message` and `Header` types now implement `Write`.
* The `Message` type received several new functions to make its API similar to that of a `Vec<u8>` or `VecDeque<u8>`.
* Implemented additional common traits on types:
	** All options: `Clone`, `Copy`, `Debug`, `Display`, `Eq`, `Hash`, `Ord`, `PartialEq`, `PartialOrd`
	** `Aio`: `Eq`, `Hash`, `PartialEq`
	** `Context`: `Eq`, `Hash`, `Ord`, `PartialEq`, `PartialOrd`
	** `Dialer`: `Copy`, `Hash`, `Ord`, `PartialOrd`
	** `Header`: `Default`
	** `Listener`: `Copy`, `Hash`, `Ord`, `PartialOrd`
	** `Message`: `Default`, `FromIterator` for both values and references of `u8`
	** `Pipe`: `Copy`, `Hash`, `Ord`, `PartialOrd`
	** `Protocol`: `Ord`, `PartialOrd`
	** `Socket`: `Hash`, `Ord`, `PartialOrd`
	** `SocketAddr`: `Ord`, `PartialOrd`

=== Changed ===

* Renamed several methods to fit the Rust API guidelines:
	** `Message::header` → `Message::as_header`
	** `Message::header_mut` → `Message::as_mut_header`
	** `Message::zeros` → `Message::with_zeros`
* All variations of the "send" operation now take `Into<Message>` instead of `Message` directly.
* All of the "close" functions now take `&self` instead of `self`.

=== Deprecated ===

=== Removed ===

* The `Body` type has been removed. Most applications do not need to touch the header, so it makes sense to mask the distinction between the body and header slightly.
* `Pipe::socket_id` has been removed as well as all of the ID related functions. (#15)

=== Fixed ===

* The IPv4 address is now in the correct order. (#28)

=== Security ===

//------------------------------------------------------------------------------
// Past Releases
//------------------------------------------------------------------------------

== [nng-rs v0.5.0-rc.1] - 2019-04-14 ==

=== Added ===

* A new "unsafe options" set of traits have been added in order to expose options that are currently not safely handled.
	** Any of these options should be considered *unstable* as they will ideally be replaced with safe versions.
* The `IPC_SECURITY_DESCRIPTOR` has been added as the first "unsafe option".
* The `PAIR1_POLY` option has been added.
* The following traits are now implemented: (#18, #23)
	** `PipeEvent`: `Debug`, `Copy`, `Clone`, `Eq`, `PartialEq`, `Hash`
	** `Protocol`: `Eq`, `PartialEq`, `Hash`
	** `SocketAddr`: `Display`, `Eq`, `PartialEq`, `Hash`

=== Changed ===

* The `ErrorKind` type has been renamed to `Error` and the old `Error` type has been deleted.
	** Additionally, the `Hash` trait has been derived for the new `Error` type.
* `Error::ProtocolError` renamed to `Error::Protocol` in order to appease Clippy.
* `Message::try_from` was renamed to `Message::from_slice`.
* Uncaught panics in a callback now cause the application to abort, matching the behavior concerning FFI boundaries that was (re)introduced in Rustc 1.33. (#6)
* The following functions now take `&self` instead of `&mut self` (#27):
	** `Socket::{dial, listen, recv, send, recv_async, send_async, pipe_notify}`.
	** `Context::{send, recv}`.

=== Removed ===

* The `nng-sys` crate has been moved to a new repository (#17).
* The `Aio::new` function now requires a callback and the non-callback version has been removed. (#24)
* The `Aio::result` function has been removed in favor of providing the result directly to the completion callback. (#24)

== [nng-rs v0.4.0] - 2019-01-27 ==

=== Added ===

* Sockets can now send messages asynchronously via `Socket::send_async`.
* Sockets can now receive messages asynchronously via `Socket::recv_async`.
* Sockets can now be cloned to have multiple handles to the same underlying NNG socket.
* `Socket::close` and `Context::close` have been added to match the style of Dialers, Pipes, and Listeners.
* Pipes and the pipe notify functionality has been implemented. (#14)

=== Changed ===

* The majority of types are now at the root of the crate rather than a module.
* Asynchronous sending on a context is now via `Context::send` rather than `Aio::send`.
* Asynchronous receiving on a context is now via `Context::recv` rather than `Aio::recv`.
* Dialers and listeners are now treated as handle values and do not close on drop.
* The PUBSUB example now publishes the number of subscribers rather than the time in order to show off the pipe notify functionality.

=== Fixed ===

* The `Push0` protocol now actually opens a `Push0` socket (instead of a `Pull0` socket).
* Asynchronous I/O callbacks no longer can enter the same callback closure simultaneously.
* `SocketAddr` now compiles on platforms where a `c_char` is unsigned. (#11)

== [nng-sys v0.1.3] - 2019-01-27 ==

=== Added ===

* Handle types now derive `PartialEq` and `Eq`.

=== Changed ===

* The `build-nng` flag no longer builds _nng_ tests or tools. (#10)
* Updated to support _nng_ v1.1.1. (#13)

== [nng-rs v0.3.0] - 2018-11-02 ==

First fully usable version.

== [nng-sys v0.1.2] - 2018-11-02 ==

First fully usable version
